### PR TITLE
Creates basic three layer setup for mouse

### PR DESCRIPTION
**Pull request by lorentrogers**
PR for discussion around #18

### CODE REVIEW

**Comment by audibleblink** [comment]
Did this end up working for you? I tried assigning each mouse action to it's own function layer like in the latest email topic, but I'm sure I borked something there

**Comment by lorentrogers** [comment]
No - this PR was just to get conversation going. But, discussion on the mailing lists revealed some great work by @maurolopes: https://github.com/maurolopes/tmk_keyboard/commit/00fe542606e9271b625787dde092960f9887273d?diff=unified

At some point I'll try this code out, but I've just not had a chance yet. (Let me know if it works for you!)

**Comment by audibleblink** [comment]
I couldn't get it work. I found a fork of someone who'd rebased from a more recent commit of the official TMK though and that worked a treat. TMK's new actionmap make so much more sense.  [My config after the update](https://github.com/audibleblink/atreus-firmware/blob/master/atreus/keymap_alex.c)

**Comment by wolfish17** [comment]
Thank you for identifying that fork and the actionmap scheme.  That has potential to resolve an issue I have been struggling with: Effective way to utilize MACRO() without using up the limited user function space. I can't wait to find time to play with that.

**Comment by technomancy** [comment]
Sorry for the massive delay on this. I've got it working using the code from @maurolopes; see `keymap_mouse.c` on 84aec74, and added a note to the readme. Thanks for your patience!

**Pull request merged**
